steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'functions', 'deploy', 'calculateTokenDailyValue',
      '--gen2',
      '--region', 'southamerica-east1',
      '--runtime', 'nodejs20',
      '--source', 'calculateTokenDailyValue/',
      '--entry-point', 'calculateTokenDailyValue',
      '--trigger-http',
      '--allow-unauthenticated'
  ]

options:
  logsBucket: 'gs://944753101931-southamerica-east1-cloudbuild-logs'